language: php
php: 
  - '7.3'
install: composer update
script:
  - $TRAVIS_BUILD_DIR/vendor/bin/phpunit $TRAVIS_BUILD_DIR/tests/
  - $TRAVIS_BUILD_DIR/vendor/bin/phpunit --coverage-clover=coverage.xml $TRAVIS_BUILD_DIR/tests/
after_success:
    - bash <(curl -s https://codecov.io/bash)

branches:
  only:
  - master
  - dev